# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160307181939 on 2016-09-21 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vemdolixo', '0003_auto_20160823_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(default=None, max_length=200)),
                ('is_used', models.IntegerField(default=0)),
                ('admin_level', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter_accepted_at', models.DateTimeField(auto_now_add=True)),
                ('push_accepted_at', models.DateTimeField(auto_now_add=True)),
                ('birthdate', models.DateTimeField(default=datetime.datetime.now)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('username', models.CharField(default=None, max_length=200)),
                ('email_activated', models.IntegerField(default=0)),
                ('phone_activated', models.IntegerField(default=0)),
                ('facebook_profile', models.CharField(default='', max_length=400)),
                ('admin_level', models.IntegerField(default=0)),
                ('profile_picture', models.CharField(default='https://s3-sa-east-1.amazonaws.com/residoando/user.svg', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='residue_association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('residue_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
